services:
  subconverter:
    build: .
    container_name: subconverter
    ports:
      - "25500:25500"
    volumes:
      - ./base/custom/pref.toml:/base/pref.toml
      - ./base/custom/ACLSSR:/base/ACL4SSR
      - ./base/custom/ACLSSR/Clash:/base/Clash
      - ./base/custom/savedconfigs:/base/custom/savedconfigs
    environment:
      - API_ACCESS_TOKEN=${API_ACCESS_TOKEN:-}
      - MANAGED_CONFIG_PREFIX=${MANAGED_CONFIG_PREFIX:-http://127.0.0.1:25500}
      - CUSTOM_PAGE_PASSWORD=${CUSTOM_PAGE_PASSWORD:-}
    restart: always
